CREATE USER IF NOT EXISTS ROOT SALT '133aa14331534b28' HASH '5d53c132054fac0409daaf729604b116c69c8c74e27936f06c4baf884b35b7cf' ADMIN;
CREATE SEQUENCE PUBLIC.CAR_SEQ START WITH 546;
CREATE SEQUENCE PUBLIC.MODEL_SEQ START WITH 500;
CREATE CACHED TABLE PUBLIC.PRODUCERS( 
    PRODUCER_ID BIGINT NOT NULL, 
    PRODUCER_NAME VARCHAR(50) NOT NULL 
);
ALTER TABLE PUBLIC.PRODUCERS ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(PRODUCER_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCERS;
CREATE CACHED TABLE PUBLIC.MODELS( 
    MODEL_ID BIGINT NOT NULL, 
    PRODUCER_ID BIGINT NOT NULL, 
    MODEL_NAME VARCHAR(50) NOT NULL 
);
ALTER TABLE PUBLIC.MODELS ADD CONSTRAINT PUBLIC.CONSTRAINT_87 PRIMARY KEY(MODEL_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MODELS;
CREATE CACHED TABLE PUBLIC.CARS( 
    CAR_ID BIGINT NOT NULL, 
    PRODUCER_ID BIGINT NOT NULL, 
    MODEL_ID BIGINT NOT NULL, 
    PRODUCTION_YEAR DATE, 
    FUEL VARCHAR(50) NOT NULL, 
    TRANSMISSION VARCHAR(50) NOT NULL 
);
ALTER TABLE PUBLIC.CARS ADD CONSTRAINT PUBLIC.CONSTRAINT_1F PRIMARY KEY(CAR_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CARS;
ALTER TABLE PUBLIC.CARS ADD CONSTRAINT PUBLIC.CONSTRAINT_1 UNIQUE(CAR_ID);
ALTER TABLE PUBLIC.PRODUCERS ADD CONSTRAINT PUBLIC.CONSTRAINT_67 UNIQUE(PRODUCER_ID);
ALTER TABLE PUBLIC.MODELS ADD CONSTRAINT PUBLIC.CONSTRAINT_8 UNIQUE(MODEL_ID);
ALTER TABLE PUBLIC.CARS ADD CONSTRAINT PUBLIC.CONSTRAINT_1F73 FOREIGN KEY(MODEL_ID) REFERENCES PUBLIC.MODELS(MODEL_ID) NOCHECK;
ALTER TABLE PUBLIC.MODELS ADD CONSTRAINT PUBLIC.CONSTRAINT_87D FOREIGN KEY(PRODUCER_ID) REFERENCES PUBLIC.PRODUCERS(PRODUCER_ID) NOCHECK;
ALTER TABLE PUBLIC.CARS ADD CONSTRAINT PUBLIC.CONSTRAINT_1F7 FOREIGN KEY(PRODUCER_ID) REFERENCES PUBLIC.PRODUCERS(PRODUCER_ID) NOCHECK;
